version: 0.{build}

platform:
- x64

environment:
  GOPATH: C:\gopath
  GOROOT: C:\go
  GLIDE_TAG: v0.13.2
  GOMETALINTER_TAG: v2.0.11
  CLONE_FOLDER: C:\gopath\src\github.com\EXCCoin\exccdata

init:
- git config --global core.autocrlf input
- set PATH=%GOROOT%\bin;%GOPATH%\bin;%PATH%
- ps: Update-AppveyorBuild -Version "$env:APPVEYOR_REPO_TAG_NAME"
- set PATH=C:\msys64\mingw64\bin;%PATH%;C:\msys64\usr\bin
- set CGO_LDFLAGS=-g -O2 -static -static-libgcc -static-libstdc++
- g++ --version
- go version
- go env
# gometalinter
- go get -v github.com/alecthomas/gometalinter
- cd %GOPATH%\src\github.com\alecthomas\gometalinter
- git checkout %GOMETALINTER_TAG%
- go install
- gometalinter --install
# tools, glide, ...
- go get -u honnef.co/go/tools/...
- if not exist %CLONE_FOLDER% mkdir %CLONE_FOLDER%
- cd %CLONE_FOLDER%

clone_folder: C:\gopath\src\github.com\EXCCoin\exccdata
clone_depth: 15

build_script:
- cd %CLONE_FOLDER%
- git reset --hard HEAD

test_script:
- gometalinter --vendor --disable-all --deadline=10m -s testdata --enable=gofmt --enable=vet --enable=gosimple --enable=unconvert --enable=ineffassign ./...
- go install . ./cmd/...
- set GORACE='halt_on_error=1'
- go test -short -race ./...